# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/SemcCameraUI/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/SemcCameraUI

PRODUCT_COPY_FILES += \
    vendor/sony/SemcCameraUI/proprietary/etc/init/cacaoserver.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/cacaoserver.rc \
    vendor/sony/SemcCameraUI/proprietary/etc/permissions/com.sonymobile.imageprocessor.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.sonymobile.imageprocessor.xml \
    vendor/sony/SemcCameraUI/proprietary/etc/default-permissions/default-permissions-sony-camera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/default-permissions/default-permissions-sony-camera.xml \
    vendor/sony/SemcCameraUI/proprietary/etc/sysconfig/sony-camera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/sony-camera.xml \
    vendor/sony/SemcCameraUI/proprietary/product/etc/permissions/com.sonymobile.camera.addon.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.sonymobile.camera.addon.xml

PRODUCT_PACKAGES += \
    SemcCameraUI-xxhdpi-release \
    CameraAddonPermission \
    CameraCommonPermission \
    CameraExtensionPermission \
    ImageProcessorPermission \
    CameraCommon \
    com.sonymobile.imageprocessor.bypasscamera_impl \
    com.sonymobile.camera.addon_impl \
    lib-camshim \
    libswregistrationalgo \
    cacaoserver \
    libcacao_client \
    libcacao_pal \
    libimageprocessorjni \
    libcacao_process_ctrl_gateway \
    libcacao_service \
    vendor.somc.hardware.camera.cacao@1.0-system \
    vendor.somc.hardware.camera.cacao@2.0-system \
    vendor.somc.hardware.camera.cacao@3.0-system \
    vendor.somc.hardware.camera.cacao@3.1-system \
    vendor.somc.hardware.camera.cacao@3.2-system \
    vendor.somc.hardware.camera.device@1.0-system \
    vendor.somc.hardware.camera.provider@1.0-system

